#pragma once

class Tile
{
private:

public:

	// Tiletypes: there are a lot of them
	const enum TileType
	{
		WALL_TOP_LEFT,
		WALL_TOP_MID,
		WALL_TOP_RIGHT,
		WALL_LEFT,
		WALL_MID,
		WALL_RIGHT,
		WALL_FOUNTAIN_TOP,
		WALL_FOUNTAIN_MID_RED_ANIM,
		WALL_FOUNTAIN_BASIN_RED_ANIM,
		WALL_FOUNTAIN_MID_BLUE_ANIM,
		WALL_FOUNTAIN_BASIN_BLUE_ANIM,
		WALL_HOLE_1,
		WALL_HOLE_2,
		WALL_BANNER_RED,
		WALL_BANNER_BLUE,
		WALL_BANNER_GREEN,
		WALL_BANNER_YELLOW,
		COLUMN_TOP,
		COLUMN_MID,
		COLUMN_BASE,
		WALL_COLUMN_TOP,
		WALL_COLUMN_MID,
		WALL_COLUMN_BASE,
		WALL_GOO,
		WALL_GOO_BASE,
		FLOOR_1,
		FLOOR_2,
		FLOOR_3,
		FLOOR_4,
		FLOOR_5,
		FLOOR_6,
		FLOOR_7,
		FLOOR_8,
		FLOOR_LADDER,
		FLOOR_SPIKES_ANIM,
		WALL_SIDE_TOP_LEFT,
		WALL_SIDE_TOP_RIGHT,
		WALL_SIDE_MID_LEFT,
		WALL_SIDE_MID_RIGHT,
		WALL_SIDE_FRONT_LEFT,
		WALL_SIDE_FRONT_RIGHT,
		WALL_CORNER_TOP_LEFT,
		WALL_CORNER_TOP_RIGHT,
		WALL_CORNER_LEFT,
		WALL_CORNER_RIGHT,
		WALL_CORNER_BOTTOM_LEFT,
		WALL_CORNER_BOTTOM_RIGHT,
		WALL_CORNER_FRONT_LEFT,
		WALL_CORNER_FRONT_RIGHT,
		WALL_INNER_CORNER_L_TOP_LEFT,
		WALL_INNER_CORNER_L_TOP_RIGHT,
		WALL_INNER_CORNER_MID_LEFT,
		WALL_INNER_CORNER_MID_RIGHT,
		WALL_INNER_CORNER_T_TOP_LEFT,
		WALL_INNER_CORNER_T_TOP_RIGHT
	};

	Tile();
};